### ISSUE TITLE
Fix: Improve input validation (e.g., prevent adding empty tasks)

### ISSUE THREAD

**Issue by lambeboluwatife** [dormeneur/To-Do-List#2]
In the javascript file, there is no check to prevent users from adding an empty task when adding a new task. 

Assign to me to work on it.

**Comment by dormeneur** [comment]
Hi @lambeboluwatife , 
Thank you for pointing out a fix for the issue!
I’d be happy to assign the task to you. Please let me know if you need further details as you work on it.
Looking forward to seeing your contributions!

**Comment by lambeboluwatife** [comment]
Okay 
I'll work on it

Please don't forget to add the hacktoberfest label.

**Comment by dormeneur** [comment]
Hi @lambeboluwatife  any progress...

**Comment by lambeboluwatife** [comment]
Hello @dormeneur I'll make a PR tonight

**Comment by lambeboluwatife** [comment]
@dormeneur I made a PR
Kindly check

**Comment by dormeneur** [comment]
Fixed.
